### ISSUE TITLE
Doesn't include results for team-review-requested

### ISSUE THREAD

**Issue by jonrohan** [rachmari/first-responder#12] opened 2021-01-07 23:50 UTC
I was expecting this pr https://github.com/primer/octicons/pull/528 to show up in the results. https://github.com/pulls?q=is%3Aopen+is%3Apr+repo%3Aprimer%2Focticons+team%3Aprimer%2Fds-core+archived%3Afalse+ using the `team:XXX` search you have on https://github.com/rachmari/first-responder/blob/41e474823a04be25bde334b9cebc7b6b64eac4f6/index.js#L75 

But according to [the search docs](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-team-mention) `team:` only searches for team mentions and doesn't search for requested reviews. We would need to use the [team-review-requested](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-pull-request-review-status-and-reviewer) search qualifier for this. But that doesn't include mentions.

So I think we should add a second search and make sure the results only include unique issues. 

cc @rachmari

**Comment by rachmari** [comment] 2021-01-12 03:12
This is something I hoped to add! I have an existing, but much less detailed, over here: https://github.com/rachmari/first-responder/issues/3. I'll close that one as a duplicate of this one.

**Closed as completed** 2022-05-19 19:40 UTC
